"use client";

import { useState } from "react";
import { Info, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { defaultAutoGenerateConfig, type AutoGenerateConfig } from "@/lib/utils/autoGenerate";

interface AutoGenerateDialogProps {
  open: boolean;
  onClose: () => void;
  onGenerate: (config: AutoGenerateConfig) => Promise<void>;
  staffCount: number;
  daysInMonth: number;
}

export function AutoGenerateDialog({
  open,
  onClose,
  onGenerate,
  staffCount,
  daysInMonth,
}: AutoGenerateDialogProps) {
  const [config, setConfig] = useState<AutoGenerateConfig>(defaultAutoGenerateConfig);
  const [loading, setLoading] = useState(false);

  function update<K extends keyof AutoGenerateConfig>(key: K, value: AutoGenerateConfig[K]) {
    setConfig((current) => ({ ...current, [key]: value }));
  }

  function updateCoverage(shift: "M" | "A" | "N", value: number) {
    setConfig((current) => ({
      ...current,
      minCoveragePerShift: { ...current.minCoveragePerShift, [shift]: value },
    }));
  }

  async function handleGenerate() {
    setLoading(true);
    try {
      await onGenerate(config);
      onClose();
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(nextOpen) => !nextOpen && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-[#2E86AB]" />
            Auto-Generate Roster
          </DialogTitle>
          <DialogDescription>
            Configure shift distribution rules before replacing this month&apos;s entries.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5">
          <div className="flex items-center gap-2 rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-sm text-blue-700">
            <Info className="h-4 w-4 shrink-0" />
            <span>
              <strong>{staffCount} active staff</strong> / {daysInMonth} days this month
            </span>
          </div>

          <fieldset className="space-y-3">
            <legend className="text-sm font-semibold text-slate-700">Shifts per staff member</legend>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              {(
                [
                  { key: "morningDaysPerStaff", label: "Morning (M)", defaultValue: 16 },
                  { key: "afternoonDaysPerStaff", label: "Afternoon (A)", defaultValue: 8 },
                  { key: "nightDaysPerStaff", label: "Night (N)", defaultValue: 4 },
                ] as const
              ).map((field) => (
                <label key={field.key} className="space-y-1 text-xs font-semibold text-slate-600">
                  {field.label}
                  <Input
                    type="number"
                    min={0}
                    max={daysInMonth}
                    value={config[field.key]}
                    onChange={(event) => update(field.key, Number(event.target.value))}
                    className="h-9"
                  />
                  <span className="block font-normal text-slate-400">default: {field.defaultValue}</span>
                </label>
              ))}
            </div>
          </fieldset>

          <fieldset className="space-y-3">
            <legend className="text-sm font-semibold text-slate-700">Annual leave entitlement</legend>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <label className="space-y-1 text-xs font-semibold text-slate-600">
                Full-time staff
                <Input
                  type="number"
                  min={0}
                  max={60}
                  value={config.annualLeaveEntitlementFullTime}
                  onChange={(event) => update("annualLeaveEntitlementFullTime", Number(event.target.value))}
                  className="h-9"
                />
                <span className="block font-normal text-slate-400">default: 30 days</span>
              </label>
              <label className="space-y-1 text-xs font-semibold text-slate-600">
                Part-time / locum
                <Input
                  type="number"
                  min={0}
                  max={30}
                  value={config.annualLeaveEntitlementPartTime}
                  onChange={(event) => update("annualLeaveEntitlementPartTime", Number(event.target.value))}
                  className="h-9"
                />
                <span className="block font-normal text-slate-400">default: 15 days</span>
              </label>
            </div>
          </fieldset>

          <fieldset className="space-y-3">
            <legend className="text-sm font-semibold text-slate-700">Minimum staff per shift</legend>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              {(["M", "A", "N"] as const).map((shift) => (
                <label key={shift} className="space-y-1 text-xs font-semibold text-slate-600">
                  {shift === "M" ? "Morning" : shift === "A" ? "Afternoon" : "Night"}
                  <Input
                    type="number"
                    min={1}
                    max={20}
                    value={config.minCoveragePerShift[shift]}
                    onChange={(event) => updateCoverage(shift, Number(event.target.value))}
                    className="h-9"
                  />
                  <span className="block font-normal text-slate-400">
                    default: {defaultAutoGenerateConfig.minCoveragePerShift[shift]}
                  </span>
                </label>
              ))}
            </div>
          </fieldset>

          <fieldset className="space-y-3">
            <legend className="text-sm font-semibold text-slate-700">Rules</legend>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <label className="space-y-1 text-xs font-semibold text-slate-600">
                Max consecutive nights
                <Input
                  type="number"
                  min={1}
                  max={7}
                  value={config.maxConsecutiveNights}
                  onChange={(event) => update("maxConsecutiveNights", Number(event.target.value))}
                  className="h-9"
                />
                <span className="block font-normal text-slate-400">default: 3</span>
              </label>
              <label className="flex items-center gap-2 self-center text-sm font-semibold text-slate-700">
                <input
                  type="checkbox"
                  checked={config.enforceSeniorCoverage}
                  onChange={(event) => update("enforceSeniorCoverage", event.target.checked)}
                  className="h-4 w-4 rounded border-slate-300"
                />
                Require senior per shift
              </label>
            </div>
          </fieldset>

          <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">
            Warning: this will replace all existing entries for this month.
          </p>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={loading}>
            Cancel
          </Button>
          <Button onClick={handleGenerate} disabled={loading} className="bg-[#1A2B4A] hover:bg-[#24395f]">
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            Generate Roster
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
